version: '3'
services:
  app:
    build: .
    container_name: f1-crawl-and-graphs
    volumes:
      - ./:/app
    command: sh -c 'cd f1-crawl && npm install && 
             cd ../f1-graphs && npm install && npm run dev'
    ports:
      - "3000:3000"